#!/usr/bin/env bash
# script for installing Install nginx web server
# Update the package index
apt-get update

# Install Nginx
apt-get install -y nginx

# Create a custom HTML page with "Hello World!"
echo "Hello World!" > /var/www/html/index.html

# restart Nginx
nginx -s reload
