#!/usr/bin/env bash
# redirection to another page following requirements
# Intall Nginx
apt-get update
apt-get install -y nginx

# Create a custom Nginx configuration
cat > /etc/nginx/sites-available/default <<EOL
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    
    server_name _;
    
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    
    location / {
        root /var/www/html;
    }
}
EOL

# Start Nginx
service nginx start

exit 0
