#!/usr/bin/env bash
#script that pings an IP address passed as an argument

# Check if an argument is provided
if [ $# -eq 0 ]; then
    echo "Usage: $0 {IP_ADDRESS}"
else
	#Ping the IP address 5 times
	ping -c 5 "$1"
fi
