#!/usr/bin/env bash
# a Bash script that configures a server to the given requirements

# remove default Nginx configuration file
rm /etc/nginx/sites-enabled/default

# Configure Nginx to listen on port 80 for all active IPv4 IPs
sed -i '/listen 80 default_server;/c\    listen 80 default_server ipv4only=on;' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
service nginx restart
