#!/bin/bash

# Find the PID of the "4-to_infinity_and_beyond" process
pid=$(pgrep -f "4-to_infinity_and_beyond")

if [ -n "$pid" ]; then
    # Terminate the process
    kill "$pid"
    echo "Terminated"
else
    echo "Process not found"
fi
