#!/usr/bin/env bash
# This script displays hours from 0 to 12 and minutes from 1 to 59

hour=0

# Display hours from 0 to 12
while [ $hour -le 12 ]; do
    echo "Hour: $hour"
    
    minute=1
    
    # Display minutes from 1 to 59
    while [ $minute -le 59 ]; do
        echo "$minute"
        ((minute++))
    done
    
    ((hour++))
done
