#!/usr/bin/env bash
#script that configures an Ubuntu server with the given requirements

# Check if script is running in Docker and as root
[[ -f /.dockerenv && $EUID -eq 0 ]] || { echo "Please run in Docker environment with root privileges. Exiting."; exit 1; }

# Configuration
hosts_file="/etc/hosts"
backup_file="${hosts_file}.bak"
entries=("127.0.0.2 localhost" "8.8.8.8 facebook.com")

# Backup hosts file
cp "$hosts_file" "$backup_file"

# Modify hosts file
echo "${entries[@]}" >> "$hosts_file"
