#!/usr/bin/env bash
#script that displays all active IPv4 IPs on the machine it’s executed on

# Get the active IPv4 IPs using 'ip' command
ipv4_addresses=$(ip -4 addr | grep -oP '(?<=inet\s)\d+(\.\d+){3}')

# Display the result
echo "$ipv4_addresses"
