#!/usr/bin/env bash
#script that listens on port 98 on localhost

# Check if the nc command is available, else exit
command -v nc >/dev/null 2>&1 || { echo >&2 "netcat (nc) is required but not installed. Aborting."; exit 1; }

# Listen on port 98
nc -l -p 98 -s localhost
